### ISSUE TITLE
AttributeError: module 'tensorflow.contrib.rnn' has no attribute 'core_rnn_cell'

### ISSUE THREAD

**Issue by sage-khan** [harisbinzia/PronouncUR#17]
On running app.py with python3 I received AttributeError: module 'tensorflow.contrib.rnn' has no attribute 'core_rnn_cell'

The whole output is as follows:

**(tf1) metanet@metanet-Precision-Tower-7810:~/ProgramFiles/pronouncUR/PronouncUR$ python3 app.py**
Loading vocabularies from itudict
WARNING:tensorflow:From /home/metanet/ProgramFiles/pronouncUR/PronouncUR/g2p.py:66: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2022-07-03 11:01:30.365847: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2022-07-03 11:01:30.406687: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: NVIDIA GeForce RTX 3080 Ti major: 8 minor: 6 memoryClockRate(GHz): 1.665
pciBusID: 0000:03:00.0
2022-07-03 11:01:30.407012: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2022-07-03 11:01:30.408631: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2022-07-03 11:01:30.410073: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2022-07-03 11:01:30.410381: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2022-07-03 11:01:30.412172: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2022-07-03 11:01:30.413463: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2022-07-03 11:01:30.417611: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2022-07-03 11:01:30.417960: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2022-07-03 11:01:30.418399: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2022-07-03 11:01:30.446934: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2394455000 Hz
2022-07-03 11:01:30.451648: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55f574bdb5c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2022-07-03 11:01:30.451699: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2022-07-03 11:01:30.699749: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55f576b8e680 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2022-07-03 11:01:30.699826: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA GeForce RTX 3080 Ti, Compute Capability 8.6
2022-07-03 11:01:30.700408: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: NVIDIA GeForce RTX 3080 Ti major: 8 minor: 6 memoryClockRate(GHz): 1.665
pciBusID: 0000:03:00.0
2022-07-03 11:01:30.700510: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2022-07-03 11:01:30.700545: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2022-07-03 11:01:30.700576: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2022-07-03 11:01:30.700610: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2022-07-03 11:01:30.700642: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2022-07-03 11:01:30.700674: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2022-07-03 11:01:30.700707: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2022-07-03 11:01:30.701298: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2022-07-03 11:01:30.701377: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2022-07-03 11:01:30.701951: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-07-03 11:01:30.701986: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2022-07-03 11:01:30.702006: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2022-07-03 11:01:30.702727: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11050 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 3080 Ti, pci bus id: 0000:03:00.0, compute capability: 8.6)
Creating 2 layers of 512 units.
WARNING:tensorflow:

WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "app.py", line 23, in <module>
    g2p_model.load_decode_model()
  File "/home/metanet/ProgramFiles/pronouncUR/PronouncUR/g2p.py", line 74, in load_decode_model
    forward_only=True)
  File "/home/metanet/ProgramFiles/pronouncUR/PronouncUR/seq2seq_model.py", line 121, in __init__
    single_cell = tf.contrib.rnn.core_rnn_cell.GRUCell(size)
AttributeError: module 'tensorflow.contrib.rnn' has no attribute 'core_rnn_cell'

**(tf1) metanet@metanet-Precision-Tower-7810:~/ProgramFiles/pronouncUR/PronouncUR$ pip show tensorflow**
Name: tensorflow
Version: 1.15.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /home/metanet/miniconda3/envs/tf1/lib/python3.7/site-packages
Requires: numpy, protobuf, absl-py, wrapt, tensorflow-estimator, opt-einsum, termcolor, keras-applications, grpcio, google-pasta, six, gast, tensorboard, keras-preprocessing, astor, wheel
Required-by: 

**(tf1) metanet@metanet-Precision-Tower-7810:~/ProgramFiles/pronouncUR/PronouncUR$**

**Comment by sage-khan** [comment]
I made a conda environment with tensorflow-gpu 1.15 and other requirements were fulfilled.

 2072  conda create -n tf1 tensorflow-gpu=1.15.0
 2073  conda activate tf1
 2074  python3 app.py
 2075  pip install flask
 2077  pip install numpy flask
 2078  python3 app.py 
 2080  pip show tensorflow
 2081  python3 app.py
 2083  pip show tensorflow
